name: Debug Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Start tmate session?'
        required: false
        type: boolean
        default: true

jobs:
  debug-session:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Free Disk Space (Slimhub)
        uses: haandol/slimhub-action@v1
        with:
          # Turn 'false' any tools you do not need during your debug session 
          # to wipe them and maximize storage.
          android: false
          dotnet: false
          haskell: false
          codeql: false
          docker: false

      - name: Check Available Space
        run: |
          echo "=== Disk Space After Slimhub ==="
          df -h
          

      - name: Start tmate session
        # Only runs if you checked the box during manual trigger
        if: ${{ github.event.inputs.debug_enabled == 'true' }}
        uses: mxschmitt/action-tmate@v3
        with: 
           limit-access-to-actor: false

      - name: Finalize Build
        run: echo "Workflow continued after tmate session was closed."
        
